// Generated by scripts/generate.py from canonical.json. Do not edit by hand.
// Regenerate with `python3 scripts/generate.py`.

import Web3Core

/// System contract and precompile addresses from `canonical.json`.
public enum DiesisAddresses {
    /// `DIESIS_STAKING`
    public static let diesisStaking = EthereumAddress("0xd1e5150000000000000000000000000000000001", ignoreChecksum: true)!
    /// `DIESIS_PATRON`
    public static let diesisPatron = EthereumAddress("0xd1e5150000000000000000000000000000000002", ignoreChecksum: true)!
    /// `DIESIS_CONFIG`
    public static let diesisConfig = EthereumAddress("0xd1e5150000000000000000000000000000000003", ignoreChecksum: true)!
    /// `BOOTSTRAP_ORACLE`
    public static let bootstrapOracle = EthereumAddress("0xd1e5150000000000000000000000000000000004", ignoreChecksum: true)!
    /// `BOOTSTRAP_CONFIG`
    public static let bootstrapConfig = EthereumAddress("0xd1e5150000000000000000000000000000000005", ignoreChecksum: true)!
    /// `DIESIS_STATE_WRITER`
    public static let diesisStateWriter = EthereumAddress("0xd1e5150000000000000000000000000000000010", ignoreChecksum: true)!
    /// `DIESIS_POSITION`
    public static let diesisPosition = EthereumAddress("0xd1e5150000000000000000000000000000000020", ignoreChecksum: true)!
    /// `DIESIS_BUNDLE_ESCROW`
    public static let diesisBundleEscrow = EthereumAddress("0xd1e515000000000000000000000000000000be5c", ignoreChecksum: true)!
    /// `WRAPPED_DS`
    public static let wrappedDs = EthereumAddress("0xd1e51500000000000000000000000000000000d5", ignoreChecksum: true)!
    /// `LIQUID_STAKED_DS`
    public static let liquidStakedDs = EthereumAddress("0xd1e51500000000000000000000000000000ac1d5", ignoreChecksum: true)!
    /// `DIESIS_TEST_USD`
    public static let diesisTestUsd = EthereumAddress("0xd1e5150000000000000000000000000000000040", ignoreChecksum: true)!
    /// `DIESIS_MARKETS`
    public static let diesisMarkets = EthereumAddress("0xd1e515000000000000000000000000000000b00c", ignoreChecksum: true)!
    /// `DIESIS_SPOT_BOOK`
    public static let diesisSpotBook = EthereumAddress("0xd1e515000000000000000000000000000000590d", ignoreChecksum: true)!
    /// `DIESIS_PERPS_BOOK`
    public static let diesisPerpsBook = EthereumAddress("0xd1e5150000000000000000000000000000009e29", ignoreChecksum: true)!
    /// `DIESIS_MARGIN`
    public static let diesisMargin = EthereumAddress("0xd1e515000000000000000000000000000000a1ce", ignoreChecksum: true)!
    /// `DIESIS_SETTLEMENT`
    public static let diesisSettlement = EthereumAddress("0xd1e5150000000000000000000000000000005e71", ignoreChecksum: true)!
    /// `DIESIS_SETTLEMENT_ROUTER`
    public static let diesisSettlementRouter = EthereumAddress("0xd1e5150000000000000000000000000000005e72", ignoreChecksum: true)!
    /// `DIESIS_CONDUCTORS`
    public static let diesisConductors = EthereumAddress("0x00d1e5150000000000000000000000000000c0de", ignoreChecksum: true)!
    /// `DIESIS_CORE_VAULT`
    public static let diesisCoreVault = EthereumAddress("0x00d1e5150000000000000000000000000000c04e", ignoreChecksum: true)!
    /// `DIESIS_ISSUANCE_AUCTION`
    public static let diesisIssuanceAuction = EthereumAddress("0x00d1e5150000000000000000000000000000a0c7", ignoreChecksum: true)!
    /// `DIESIS_BUYBACK_BURN`
    public static let diesisBuybackBurn = EthereumAddress("0x0d1e51500000000000000000000000000000bb07", ignoreChecksum: true)!
    /// `DIESIS_OPERATOR_BOND`
    public static let diesisOperatorBond = EthereumAddress("0x00d1e5150000000000000000000000000000bacd", ignoreChecksum: true)!
    /// `DIESIS_ERC20_FACTORY`
    public static let diesisErc20Factory = EthereumAddress("0x00d1e5150000000000000000000000000000f00c", ignoreChecksum: true)!
    /// `DIESIS_PERP_DEPLOY`
    public static let diesisPerpDeploy = EthereumAddress("0x00d1e5150000000000000000000000000000defb", ignoreChecksum: true)!
    /// `DIESIS_NAME_REGISTRY`
    public static let diesisNameRegistry = EthereumAddress("0xd1e5150000000000000000000000000000000050", ignoreChecksum: true)!
    /// `DIESIS_BASE_REGISTRAR`
    public static let diesisBaseRegistrar = EthereumAddress("0xd1e5150000000000000000000000000000000051", ignoreChecksum: true)!
    /// `DIESIS_PUBLIC_RESOLVER`
    public static let diesisPublicResolver = EthereumAddress("0xd1e5150000000000000000000000000000000052", ignoreChecksum: true)!
    /// `DIESIS_REVERSE_REGISTRAR`
    public static let diesisReverseRegistrar = EthereumAddress("0xd1e5150000000000000000000000000000000053", ignoreChecksum: true)!
    /// `DIESIS_NAME_VERIFIER`
    public static let diesisNameVerifier = EthereumAddress("0xd1e5150000000000000000000000000000000054", ignoreChecksum: true)!
    /// `DIESIS_NAME_POLICY`
    public static let diesisNamePolicy = EthereumAddress("0xd1e5150000000000000000000000000000000055", ignoreChecksum: true)!
    /// `VRF`
    public static let vrf = EthereumAddress("0xd1e5150000000000000000000000000000005eed", ignoreChecksum: true)!
    /// `STEALTH_REGISTRY`
    public static let stealthRegistry = EthereumAddress("0xd1e5150000000000000000000000000000facade", ignoreChecksum: true)!
    /// `STEALTH_ANNOUNCER`
    public static let stealthAnnouncer = EthereumAddress("0xd1e515000000000000000000000000000000ca5e", ignoreChecksum: true)!
    /// `SHIELDED_POOL`
    public static let shieldedPool = EthereumAddress("0xd1e515000000000000000000000000000000fade", ignoreChecksum: true)!
    /// `PRIVACY_POOLS`
    public static let privacyPools = EthereumAddress("0xd1e5150000000000000000000000000000deface", ignoreChecksum: true)!
    /// `GROTH16_VERIFIER`
    public static let groth16Verifier = EthereumAddress("0xd1e515000000000000000000000000000000deed", ignoreChecksum: true)!
    /// `SECP256R1`
    public static let secp256r1 = EthereumAddress("0x0000000000000000000000000000000000000100", ignoreChecksum: true)!
    /// `POSEIDON`
    public static let poseidon = EthereumAddress("0x0000000000000000000000000000000000000200", ignoreChecksum: true)!
    /// `ML_DSA`
    public static let mlDsa = EthereumAddress("0x0000000000000000000000000000000000000300", ignoreChecksum: true)!
    /// `MULTICALL3`
    public static let multicall3 = EthereumAddress("0xca11bde05977b3631167028862be2a173976ca11", ignoreChecksum: true)!
    /// `PERMIT2`
    public static let permit2 = EthereumAddress("0x000000000022d473030f116ddee9f6b43ac78ba3", ignoreChecksum: true)!

    /// Every address keyed by its `canonical.json` constant name.
    public static let all: [String: EthereumAddress] = [
        "DIESIS_STAKING": diesisStaking,
        "DIESIS_PATRON": diesisPatron,
        "DIESIS_CONFIG": diesisConfig,
        "BOOTSTRAP_ORACLE": bootstrapOracle,
        "BOOTSTRAP_CONFIG": bootstrapConfig,
        "DIESIS_STATE_WRITER": diesisStateWriter,
        "DIESIS_POSITION": diesisPosition,
        "DIESIS_BUNDLE_ESCROW": diesisBundleEscrow,
        "WRAPPED_DS": wrappedDs,
        "LIQUID_STAKED_DS": liquidStakedDs,
        "DIESIS_TEST_USD": diesisTestUsd,
        "DIESIS_MARKETS": diesisMarkets,
        "DIESIS_SPOT_BOOK": diesisSpotBook,
        "DIESIS_PERPS_BOOK": diesisPerpsBook,
        "DIESIS_MARGIN": diesisMargin,
        "DIESIS_SETTLEMENT": diesisSettlement,
        "DIESIS_SETTLEMENT_ROUTER": diesisSettlementRouter,
        "DIESIS_CONDUCTORS": diesisConductors,
        "DIESIS_CORE_VAULT": diesisCoreVault,
        "DIESIS_ISSUANCE_AUCTION": diesisIssuanceAuction,
        "DIESIS_BUYBACK_BURN": diesisBuybackBurn,
        "DIESIS_OPERATOR_BOND": diesisOperatorBond,
        "DIESIS_ERC20_FACTORY": diesisErc20Factory,
        "DIESIS_PERP_DEPLOY": diesisPerpDeploy,
        "DIESIS_NAME_REGISTRY": diesisNameRegistry,
        "DIESIS_BASE_REGISTRAR": diesisBaseRegistrar,
        "DIESIS_PUBLIC_RESOLVER": diesisPublicResolver,
        "DIESIS_REVERSE_REGISTRAR": diesisReverseRegistrar,
        "DIESIS_NAME_VERIFIER": diesisNameVerifier,
        "DIESIS_NAME_POLICY": diesisNamePolicy,
        "VRF": vrf,
        "STEALTH_REGISTRY": stealthRegistry,
        "STEALTH_ANNOUNCER": stealthAnnouncer,
        "SHIELDED_POOL": shieldedPool,
        "PRIVACY_POOLS": privacyPools,
        "GROTH16_VERIFIER": groth16Verifier,
        "SECP256R1": secp256r1,
        "POSEIDON": poseidon,
        "ML_DSA": mlDsa,
        "MULTICALL3": multicall3,
        "PERMIT2": permit2,
    ]
}
