// Generated by scripts/generate.py from canonical.json. Do not edit by hand.
// Regenerate with `python3 scripts/generate.py`.

import Foundation

extension DiesisChain {
    /// Diesis (chain ID 1980).
    public static let diesis = DiesisChain(
        id: 1980,
        name: "Diesis",
        nativeCurrency: DiesisNativeCurrency(
            name: "DS",
            symbol: "DS",
            decimals: 18
        ),
        rpcURL: URL(string: "https://rpc.diesis.xyz")!,
        explorerURL: URL(string: "https://explorer.diesis.xyz")!,
        isTestnet: false
    )

    /// Diesis Testnet (chain ID 19803).
    public static let diesisTestnet = DiesisChain(
        id: 19803,
        name: "Diesis Testnet",
        nativeCurrency: DiesisNativeCurrency(
            name: "DS",
            symbol: "DS",
            decimals: 18
        ),
        rpcURL: URL(string: "https://rpc.testnet.diesis.xyz")!,
        explorerURL: URL(string: "https://explorer.testnet.diesis.xyz")!,
        isTestnet: true
    )

    /// Every Diesis network in `canonical.json`.
    public static let all: [DiesisChain] = [diesis, diesisTestnet]
}
