// Generated by scripts/generate.py from canonical.json and the public contract list. Do not edit by hand.
// Regenerate with `python3 scripts/generate.py`.

/// Each public system contract with a fixed address, paired with its
/// address and ABI. Keys match the TypeScript SDK's `diesisContracts`.
public enum DiesisContracts {
    /// `IDiesisMarkets` at `DIESIS_MARKETS`.
    public static let markets = DiesisContract(
        key: "markets",
        name: "IDiesisMarkets",
        address: DiesisAddresses.diesisMarkets,
        abi: IDiesisMarkets.abi
    )

    /// `IDiesisSpotBook` at `DIESIS_SPOT_BOOK`.
    public static let spotBook = DiesisContract(
        key: "spotBook",
        name: "IDiesisSpotBook",
        address: DiesisAddresses.diesisSpotBook,
        abi: IDiesisSpotBook.abi
    )

    /// `IDiesisPerpsBook` at `DIESIS_PERPS_BOOK`.
    public static let perpsBook = DiesisContract(
        key: "perpsBook",
        name: "IDiesisPerpsBook",
        address: DiesisAddresses.diesisPerpsBook,
        abi: IDiesisPerpsBook.abi
    )

    /// `IDiesisMargin` at `DIESIS_MARGIN`.
    public static let margin = DiesisContract(
        key: "margin",
        name: "IDiesisMargin",
        address: DiesisAddresses.diesisMargin,
        abi: IDiesisMargin.abi
    )

    /// `IDiesisSettlement` at `DIESIS_SETTLEMENT`.
    public static let settlement = DiesisContract(
        key: "settlement",
        name: "IDiesisSettlement",
        address: DiesisAddresses.diesisSettlement,
        abi: IDiesisSettlement.abi
    )

    /// `DiesisSettlementRouter` at `DIESIS_SETTLEMENT_ROUTER`.
    public static let settlementRouter = DiesisContract(
        key: "settlementRouter",
        name: "DiesisSettlementRouter",
        address: DiesisAddresses.diesisSettlementRouter,
        abi: DiesisSettlementRouter.abi
    )

    /// `IDiesisConductors` at `DIESIS_CONDUCTORS`.
    public static let conductors = DiesisContract(
        key: "conductors",
        name: "IDiesisConductors",
        address: DiesisAddresses.diesisConductors,
        abi: IDiesisConductors.abi
    )

    /// `IDiesisErc20Factory` at `DIESIS_ERC20_FACTORY`.
    public static let erc20Factory = DiesisContract(
        key: "erc20Factory",
        name: "IDiesisErc20Factory",
        address: DiesisAddresses.diesisErc20Factory,
        abi: IDiesisErc20Factory.abi
    )

    /// `IDiesisPerpDeploy` at `DIESIS_PERP_DEPLOY`.
    public static let perpDeploy = DiesisContract(
        key: "perpDeploy",
        name: "IDiesisPerpDeploy",
        address: DiesisAddresses.diesisPerpDeploy,
        abi: IDiesisPerpDeploy.abi
    )

    /// `IDiesisOperatorBond` at `DIESIS_OPERATOR_BOND`.
    public static let operatorBond = DiesisContract(
        key: "operatorBond",
        name: "IDiesisOperatorBond",
        address: DiesisAddresses.diesisOperatorBond,
        abi: IDiesisOperatorBond.abi
    )

    /// `IDiesisBundleEscrow` at `DIESIS_BUNDLE_ESCROW`.
    public static let bundleEscrow = DiesisContract(
        key: "bundleEscrow",
        name: "IDiesisBundleEscrow",
        address: DiesisAddresses.diesisBundleEscrow,
        abi: IDiesisBundleEscrow.abi
    )

    /// `DiesisStaking` at `DIESIS_STAKING`.
    public static let staking = DiesisContract(
        key: "staking",
        name: "DiesisStaking",
        address: DiesisAddresses.diesisStaking,
        abi: DiesisStaking.abi
    )

    /// `IDiesisPosition` at `DIESIS_POSITION`.
    public static let position = DiesisContract(
        key: "position",
        name: "IDiesisPosition",
        address: DiesisAddresses.diesisPosition,
        abi: IDiesisPosition.abi
    )

    /// `ILiquidStakedDS` at `LIQUID_STAKED_DS`.
    public static let liquidStakedDS = DiesisContract(
        key: "liquidStakedDS",
        name: "ILiquidStakedDS",
        address: DiesisAddresses.liquidStakedDs,
        abi: ILiquidStakedDS.abi
    )

    /// `IWrappedDS` at `WRAPPED_DS`.
    public static let wrappedDS = DiesisContract(
        key: "wrappedDS",
        name: "IWrappedDS",
        address: DiesisAddresses.wrappedDs,
        abi: IWrappedDS.abi
    )

    /// `DiesisPatron` at `DIESIS_PATRON`.
    public static let patron = DiesisContract(
        key: "patron",
        name: "DiesisPatron",
        address: DiesisAddresses.diesisPatron,
        abi: DiesisPatron.abi
    )

    /// `DiesisConfig` at `DIESIS_CONFIG`.
    public static let config = DiesisContract(
        key: "config",
        name: "DiesisConfig",
        address: DiesisAddresses.diesisConfig,
        abi: DiesisConfig.abi
    )

    /// `IDiesisCoreVault` at `DIESIS_CORE_VAULT`.
    public static let coreVault = DiesisContract(
        key: "coreVault",
        name: "IDiesisCoreVault",
        address: DiesisAddresses.diesisCoreVault,
        abi: IDiesisCoreVault.abi
    )

    /// `IDiesisIssuanceAuction` at `DIESIS_ISSUANCE_AUCTION`.
    public static let issuanceAuction = DiesisContract(
        key: "issuanceAuction",
        name: "IDiesisIssuanceAuction",
        address: DiesisAddresses.diesisIssuanceAuction,
        abi: IDiesisIssuanceAuction.abi
    )

    /// `IDiesisBuybackBurn` at `DIESIS_BUYBACK_BURN`.
    public static let buybackBurn = DiesisContract(
        key: "buybackBurn",
        name: "IDiesisBuybackBurn",
        address: DiesisAddresses.diesisBuybackBurn,
        abi: IDiesisBuybackBurn.abi
    )

    /// `DiesisShieldedPool` at `SHIELDED_POOL`.
    public static let shieldedPool = DiesisContract(
        key: "shieldedPool",
        name: "DiesisShieldedPool",
        address: DiesisAddresses.shieldedPool,
        abi: DiesisShieldedPool.abi
    )

    /// `DiesisPrivacyPools` at `PRIVACY_POOLS`.
    public static let privacyPools = DiesisContract(
        key: "privacyPools",
        name: "DiesisPrivacyPools",
        address: DiesisAddresses.privacyPools,
        abi: DiesisPrivacyPools.abi
    )

    /// `IDiesisNameRegistry` at `DIESIS_NAME_REGISTRY`.
    public static let nameRegistry = DiesisContract(
        key: "nameRegistry",
        name: "IDiesisNameRegistry",
        address: DiesisAddresses.diesisNameRegistry,
        abi: IDiesisNameRegistry.abi
    )

    /// `DiesisBaseRegistrar` at `DIESIS_BASE_REGISTRAR`.
    public static let baseRegistrar = DiesisContract(
        key: "baseRegistrar",
        name: "DiesisBaseRegistrar",
        address: DiesisAddresses.diesisBaseRegistrar,
        abi: DiesisBaseRegistrar.abi
    )

    /// `DiesisPublicResolver` at `DIESIS_PUBLIC_RESOLVER`.
    public static let publicResolver = DiesisContract(
        key: "publicResolver",
        name: "DiesisPublicResolver",
        address: DiesisAddresses.diesisPublicResolver,
        abi: DiesisPublicResolver.abi
    )

    /// `IDiesisReverseRegistrar` at `DIESIS_REVERSE_REGISTRAR`.
    public static let reverseRegistrar = DiesisContract(
        key: "reverseRegistrar",
        name: "IDiesisReverseRegistrar",
        address: DiesisAddresses.diesisReverseRegistrar,
        abi: IDiesisReverseRegistrar.abi
    )

    /// `IDiesisNameVerifier` at `DIESIS_NAME_VERIFIER`.
    public static let nameVerifier = DiesisContract(
        key: "nameVerifier",
        name: "IDiesisNameVerifier",
        address: DiesisAddresses.diesisNameVerifier,
        abi: IDiesisNameVerifier.abi
    )

    /// `IDiesisNamePolicy` at `DIESIS_NAME_POLICY`.
    public static let namePolicy = DiesisContract(
        key: "namePolicy",
        name: "IDiesisNamePolicy",
        address: DiesisAddresses.diesisNamePolicy,
        abi: IDiesisNamePolicy.abi
    )

    /// All fixed-address contracts, in the TypeScript SDK's order.
    public static let all: [DiesisContract] = [
        markets,
        spotBook,
        perpsBook,
        margin,
        settlement,
        settlementRouter,
        conductors,
        erc20Factory,
        perpDeploy,
        operatorBond,
        bundleEscrow,
        staking,
        position,
        liquidStakedDS,
        wrappedDS,
        patron,
        config,
        coreVault,
        issuanceAuction,
        buybackBurn,
        shieldedPool,
        privacyPools,
        nameRegistry,
        baseRegistrar,
        publicResolver,
        reverseRegistrar,
        nameVerifier,
        namePolicy,
    ]
}
