#!/usr/bin/env python3
"""Regenerate the Swift bindings, addresses, chains, and contract table.

Usage:
    python3 scripts/generate.py          # regenerate everything in place
    python3 scripts/generate.py --check  # fail if anything is out of date

Inputs:
    DIESIS_CONTRACTS_DIR  contracts checkout with compiled artifacts in out/
                          (default: ../../diesis-core/diesis/contracts)
    ABI_TYPEGEN           abi-typegen binary, 0.8.0 or later
                          (default: <contracts>/node_modules/.bin/abi-typegen)
    ../diesis-js/canonical.json  source of the vendored canonical.json

Uses only the Python standard library.
"""

from __future__ import annotations

import argparse
import difflib
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCES = ROOT / "Sources" / "Diesis"
GENERATED_DIR = SOURCES / "Generated"
CANONICAL = ROOT / "canonical.json"
SDK_CANONICAL = ROOT.parent / "diesis-js" / "canonical.json"

# Same list, keys, and order as diesis-js/scripts/generate-contract-bindings.mjs.
# (key, contract name, address constant). IValidatorShare has no fixed address.
PUBLIC_CONTRACTS: list[tuple[str, str, str | None]] = [
    ("markets", "IDiesisMarkets", "DIESIS_MARKETS"),
    ("spotBook", "IDiesisSpotBook", "DIESIS_SPOT_BOOK"),
    ("perpsBook", "IDiesisPerpsBook", "DIESIS_PERPS_BOOK"),
    ("margin", "IDiesisMargin", "DIESIS_MARGIN"),
    ("settlement", "IDiesisSettlement", "DIESIS_SETTLEMENT"),
    ("settlementRouter", "DiesisSettlementRouter", "DIESIS_SETTLEMENT_ROUTER"),
    ("conductors", "IDiesisConductors", "DIESIS_CONDUCTORS"),
    ("erc20Factory", "IDiesisErc20Factory", "DIESIS_ERC20_FACTORY"),
    ("perpDeploy", "IDiesisPerpDeploy", "DIESIS_PERP_DEPLOY"),
    ("operatorBond", "IDiesisOperatorBond", "DIESIS_OPERATOR_BOND"),
    ("bundleEscrow", "IDiesisBundleEscrow", "DIESIS_BUNDLE_ESCROW"),
    ("staking", "DiesisStaking", "DIESIS_STAKING"),
    ("position", "IDiesisPosition", "DIESIS_POSITION"),
    ("validatorShare", "IValidatorShare", None),
    ("liquidStakedDS", "ILiquidStakedDS", "LIQUID_STAKED_DS"),
    ("wrappedDS", "IWrappedDS", "WRAPPED_DS"),
    ("patron", "DiesisPatron", "DIESIS_PATRON"),
    ("config", "DiesisConfig", "DIESIS_CONFIG"),
    ("coreVault", "IDiesisCoreVault", "DIESIS_CORE_VAULT"),
    ("issuanceAuction", "IDiesisIssuanceAuction", "DIESIS_ISSUANCE_AUCTION"),
    ("buybackBurn", "IDiesisBuybackBurn", "DIESIS_BUYBACK_BURN"),
    ("shieldedPool", "DiesisShieldedPool", "SHIELDED_POOL"),
    ("privacyPools", "DiesisPrivacyPools", "PRIVACY_POOLS"),
    ("nameRegistry", "IDiesisNameRegistry", "DIESIS_NAME_REGISTRY"),
    ("baseRegistrar", "DiesisBaseRegistrar", "DIESIS_BASE_REGISTRAR"),
    ("publicResolver", "DiesisPublicResolver", "DIESIS_PUBLIC_RESOLVER"),
    ("reverseRegistrar", "IDiesisReverseRegistrar", "DIESIS_REVERSE_REGISTRAR"),
    ("nameVerifier", "IDiesisNameVerifier", "DIESIS_NAME_VERIFIER"),
    ("namePolicy", "IDiesisNamePolicy", "DIESIS_NAME_POLICY"),
]

HEADER = (
    "// Generated by scripts/generate.py from {source}. Do not edit by hand.\n"
    "// Regenerate with `python3 scripts/generate.py`.\n"
)

def contracts_dir() -> Path:
    env = os.environ.get("DIESIS_CONTRACTS_DIR")
    return Path(env).resolve() if env else (ROOT.parent.parent / "diesis-core" / "diesis" / "contracts").resolve()


def typegen_bin(contracts: Path) -> Path:
    env = os.environ.get("ABI_TYPEGEN")
    return Path(env).resolve() if env else contracts / "node_modules" / ".bin" / "abi-typegen"


def lower_camel(constant: str) -> str:
    parts = constant.lower().split("_")
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def swift_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


# abi-typegen ----------------------------------------------------------------

MIN_TYPEGEN = (0, 8, 0)


def check_typegen_version(binary: Path) -> None:
    out = subprocess.run(
        [str(binary), "--version"], check=True, capture_output=True, text=True
    ).stdout
    m = re.search(r"(\d+)\.(\d+)\.(\d+)", out)
    if not m:
        raise SystemExit(f"cannot parse abi-typegen version from {out!r}")
    version = tuple(int(g) for g in m.groups())
    if version < MIN_TYPEGEN:
        want = ".".join(map(str, MIN_TYPEGEN))
        raise SystemExit(f"abi-typegen {m.group(0)} is too old; need {want} or later")


def run_typegen(contracts: Path) -> dict[str, str]:
    binary = typegen_bin(contracts)
    if not binary.exists():
        raise SystemExit(f"abi-typegen not found at {binary}; set ABI_TYPEGEN")
    check_typegen_version(binary)
    names = ",".join(name for _, name, _ in PUBLIC_CONTRACTS)
    with tempfile.TemporaryDirectory(prefix="diesis-swift-typegen-") as tmp:
        subprocess.run(
            [
                str(binary), "generate",
                "--artifacts", str(contracts / "out"),
                "--out", tmp,
                "--target", "swift",
                "--contracts", names,
            ],
            check=True,
            stdout=subprocess.DEVNULL,
        )
        produced = sorted(Path(tmp).glob("*.swift"))
        expected = {f"{name}.swift" for _, name, _ in PUBLIC_CONTRACTS}
        got = {p.name for p in produced}
        if got != expected:
            raise SystemExit(
                f"abi-typegen output mismatch: missing {sorted(expected - got)}, "
                f"extra {sorted(got - expected)}"
            )
        return {p.name: p.read_text(encoding="utf-8") for p in produced}


# canonical.json outputs -----------------------------------------------------


def render_addresses(canonical: dict) -> str:
    lines = [
        HEADER.format(source="canonical.json"),
        "import Web3Core",
        "",
        "/// System contract and precompile addresses from `canonical.json`.",
        "public enum DiesisAddresses {",
    ]
    for constant, address in canonical["addresses"].items():
        lines.append(f"    /// `{constant}`")
        lines.append(
            f"    public static let {lower_camel(constant)} = "
            f"EthereumAddress({swift_string(address)}, ignoreChecksum: true)!"
        )
    lines.append("")
    lines.append("    /// Every address keyed by its `canonical.json` constant name.")
    lines.append("    public static let all: [String: EthereumAddress] = [")
    for constant in canonical["addresses"]:
        lines.append(f"        {swift_string(constant)}: {lower_camel(constant)},")
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_chains(canonical: dict) -> str:
    names = {"mainnet": "diesis", "testnet": "diesisTestnet"}
    lines = [
        HEADER.format(source="canonical.json"),
        "import Foundation",
        "",
        "extension DiesisChain {",
    ]
    for key, chain in canonical["chains"].items():
        ident = names.get(key, lower_camel(key))
        cur = chain["nativeCurrency"]
        lines += [
            f"    /// {chain['name']} (chain ID {chain['id']}).",
            f"    public static let {ident} = DiesisChain(",
            f"        id: {chain['id']},",
            f"        name: {swift_string(chain['name'])},",
            "        nativeCurrency: DiesisNativeCurrency(",
            f"            name: {swift_string(cur['name'])},",
            f"            symbol: {swift_string(cur['symbol'])},",
            f"            decimals: {cur['decimals']}",
            "        ),",
            f"        rpcURL: URL(string: {swift_string(chain['rpcUrl'])})!,",
            f"        explorerURL: URL(string: {swift_string(chain['explorerUrl'])})!,",
            f"        isTestnet: {'true' if chain['testnet'] else 'false'}",
            "    )",
            "",
        ]
    all_idents = ", ".join(names.get(k, lower_camel(k)) for k in canonical["chains"])
    lines.append("    /// Every Diesis network in `canonical.json`.")
    lines.append(f"    public static let all: [DiesisChain] = [{all_idents}]")
    lines.append("}")
    return "\n".join(lines) + "\n"


def render_contracts(canonical: dict) -> str:
    lines = [
        HEADER.format(source="canonical.json and the public contract list"),
        "/// Each public system contract with a fixed address, paired with its",
        "/// address and ABI. Keys match the TypeScript SDK's `diesisContracts`.",
        "public enum DiesisContracts {",
    ]
    fixed = [(k, n, c) for k, n, c in PUBLIC_CONTRACTS if c is not None]
    for key, name, constant in fixed:
        if constant not in canonical["addresses"]:
            raise SystemExit(f"{constant} missing from canonical.json")
        lines += [
            f"    /// `{name}` at `{constant}`.",
            f"    public static let {key} = DiesisContract(",
            f"        key: {swift_string(key)},",
            f"        name: {swift_string(name)},",
            f"        address: DiesisAddresses.{lower_camel(constant)},",
            f"        abi: {name}.abi",
            "    )",
            "",
        ]
    lines.append("    /// All fixed-address contracts, in the TypeScript SDK's order.")
    lines.append("    public static let all: [DiesisContract] = [")
    lines.extend(f"        {key}," for key, _, _ in fixed)
    lines.append("    ]")
    lines.append("}")
    return "\n".join(lines) + "\n"


# driver ---------------------------------------------------------------------


def build_outputs(contracts: Path, canonical_text: str) -> dict[Path, str]:
    canonical = json.loads(canonical_text)
    outputs: dict[Path, str] = {CANONICAL: canonical_text}
    for fname, text in run_typegen(contracts).items():
        outputs[GENERATED_DIR / fname] = text
    outputs[SOURCES / "Addresses.swift"] = render_addresses(canonical)
    outputs[SOURCES / "Chains+Generated.swift"] = render_chains(canonical)
    outputs[SOURCES / "Contracts+Generated.swift"] = render_contracts(canonical)
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if outputs are stale")
    args = parser.parse_args()

    contracts = contracts_dir()
    if not (contracts / "out").is_dir():
        raise SystemExit(f"no compiled artifacts at {contracts / 'out'}; set DIESIS_CONTRACTS_DIR")

    if args.check:
        if not SDK_CANONICAL.exists():
            raise SystemExit(f"{SDK_CANONICAL} not found; cannot check canonical.json")
        canonical_text = SDK_CANONICAL.read_text(encoding="utf-8")
    elif SDK_CANONICAL.exists():
        canonical_text = SDK_CANONICAL.read_text(encoding="utf-8")
    else:
        print(f"note: {SDK_CANONICAL} not found; using vendored canonical.json", file=sys.stderr)
        canonical_text = CANONICAL.read_text(encoding="utf-8")

    outputs = build_outputs(contracts, canonical_text)

    if args.check:
        stale: list[str] = []
        for path, text in outputs.items():
            current = path.read_text(encoding="utf-8") if path.exists() else None
            if current != text:
                stale.append(str(path.relative_to(ROOT)))
                if current is not None:
                    sys.stdout.writelines(
                        list(difflib.unified_diff(
                            current.splitlines(True), text.splitlines(True),
                            str(path.relative_to(ROOT)), "expected", n=1,
                        ))[:40]
                    )
        extra = sorted(
            str(p.relative_to(ROOT)) for p in GENERATED_DIR.glob("*.swift") if p not in outputs
        )
        stale += [f"{p} (not produced by generator)" for p in extra]
        if stale:
            print("stale generated files:\n  " + "\n  ".join(stale), file=sys.stderr)
            return 1
        print("generated files are up to date")
        return 0

    if GENERATED_DIR.exists():
        shutil.rmtree(GENERATED_DIR)
    GENERATED_DIR.mkdir(parents=True)
    for path, text in outputs.items():
        path.write_text(text, encoding="utf-8")
    print(f"wrote {len(outputs)} files")
    return 0


if __name__ == "__main__":
    sys.exit(main())
